#!/usr/bin/env php
<?php

require dirname(__FILE__) . '/Config.php';

$commandsToRun = $CONFIG['preCommit'];
if (!is_array($commandsToRun)) exit(0);

foreach ($commandsToRun as $command) {
    $output = array();
    $return = 0;
    exec(".git/hooks/{$command}", $output, $return);
    if ($return != 0) {
        echo implode("\n", $output) . "\n";
        exit(1);
    }
}
